const db = require('./db');

async function initSchema() {
  try {
    await db.query(`
      CREATE TABLE IF NOT EXISTS team_riddle_progress (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        team_id BIGINT NOT NULL REFERENCES teams(id),
        riddle_index INTEGER NOT NULL,
        is_solved BOOLEAN NOT NULL DEFAULT false,
        solved_digit VARCHAR(10),
        solved_at TIMESTAMP(6) WITH TIME ZONE,
        solved_by_player_id BIGINT REFERENCES players(id),
        wrong_attempts INTEGER NOT NULL DEFAULT 0,
        last_attempt_at TIMESTAMP(6) WITH TIME ZONE,
        created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
        CONSTRAINT uq_team_riddle UNIQUE (team_id, riddle_index)
      )
    `);

    // Synchronize sequences to prevent duplicate key errors after manual/seed inserts
    const tables = ['events', 'teams', 'players', 'game_sessions', 'levels', 'questions'];
    for (const table of tables) {
      try {
        await db.query(`
          SELECT setval(
            pg_get_serial_sequence('${table}', 'id'),
            COALESCE((SELECT MAX(id) FROM ${table}), 1)
          )
        `);
      } catch (e) {
        // Table or sequence might not exist yet; ignore
      }
    }
  } catch (err) {
    console.warn('initSchema notice:', err.message);
  }
}

module.exports = initSchema;
