const db = require('./db');

async function initSchema() {
  try {
    await db.query(`
      CREATE TABLE IF NOT EXISTS team_riddle_progress (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        team_id BIGINT NOT NULL REFERENCES teams(id),
        riddle_index INTEGER NOT NULL,
        is_solved BOOLEAN NOT NULL DEFAULT false,
        solved_digit VARCHAR(10),
        solved_at TIMESTAMP(6) WITH TIME ZONE,
        solved_by_player_id BIGINT REFERENCES players(id),
        wrong_attempts INTEGER NOT NULL DEFAULT 0,
        last_attempt_at TIMESTAMP(6) WITH TIME ZONE,
        created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
        CONSTRAINT uq_team_riddle UNIQUE (team_id, riddle_index)
      )
    `);
  } catch (err) {
    console.warn('initSchema notice:', err.message);
  }
}

module.exports = initSchema;
