CREATE TABLE levels (
    id BIGSERIAL PRIMARY KEY,
    level_number INT NOT NULL UNIQUE CHECK (level_number BETWEEN 1 AND 6),
    name VARCHAR(100) NOT NULL,
    description TEXT,
    difficulty VARCHAR(50) DEFAULT 'MEDIUM',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX idx_levels_number ON levels(level_number);
