UPDATE levels
SET name = 'LEVEL ' || level_number,
    description = 'Neutral cooperative puzzle level ' || level_number
WHERE level_number BETWEEN 1 AND 6;

UPDATE questions SET stage_number = 1 WHERE level_id IN (SELECT id FROM levels WHERE level_number BETWEEN 1 AND 6);

UPDATE questions SET evidence = 'LEVEL 1 / STAGE 1 / PRIVATE ARTIFACT A: ordered transition records A-3, A-1, A-4.', instructions = 'Compare this record with the teammate artifact. Identify the shared ordering rule and submit the neutral discovery.', puzzle_context = 'STAGE 1', expected_answer_hash = 'ORDER-A', answer_type = 'TEXT', technical_category = 'COOPERATIVE', difficulty = 'MEDIUM' WHERE id = 1;
UPDATE questions SET evidence = 'LEVEL 1 / STAGE 1 / PRIVATE ARTIFACT B: component map A-1 -> slot 2, A-3 -> slot 1, A-4 -> slot 3.', instructions = 'Compare this map with the teammate artifact. Identify the shared ordering rule and submit the neutral discovery.', puzzle_context = 'STAGE 1', expected_answer_hash = 'ORDER-A', answer_type = 'TEXT', technical_category = 'COOPERATIVE', difficulty = 'MEDIUM' WHERE id = 2;
UPDATE questions SET evidence = 'LEVEL 2 / STAGE 1 / PRIVATE ARTIFACT A: fragment labels F2, F4, F1 with repeated boundary marker.', instructions = 'Match the boundary marker with the teammate artifact and submit the shared reconstruction rule.', puzzle_context = 'STAGE 1', expected_answer_hash = 'RULE-B', answer_type = 'TEXT', technical_category = 'COOPERATIVE', difficulty = 'MEDIUM' WHERE id = 3;
UPDATE questions SET evidence = 'LEVEL 2 / STAGE 1 / PRIVATE ARTIFACT B: fragment labels F3, F1, F2 with a different boundary marker.', instructions = 'Match the boundary marker with the teammate artifact and submit the shared reconstruction rule.', puzzle_context = 'STAGE 1', expected_answer_hash = 'RULE-B', answer_type = 'TEXT', technical_category = 'COOPERATIVE', difficulty = 'MEDIUM' WHERE id = 4;
UPDATE questions SET evidence = 'LEVEL 3 / STAGE 1 / PRIVATE ARTIFACT A: links A-B and B-D are confirmed; A-C is unverified.', instructions = 'Compare the confirmed links with the teammate topology fragment and submit the shared valid path label.', puzzle_context = 'STAGE 1', expected_answer_hash = 'LINK-C', answer_type = 'TEXT', technical_category = 'COOPERATIVE', difficulty = 'MEDIUM' WHERE id = 5;
UPDATE questions SET evidence = 'LEVEL 3 / STAGE 1 / PRIVATE ARTIFACT B: links D-E and B-C are confirmed; C-E is decoy data.', instructions = 'Compare the confirmed links with the teammate topology fragment and submit the shared valid path label.', puzzle_context = 'STAGE 1', expected_answer_hash = 'LINK-C', answer_type = 'TEXT', technical_category = 'COOPERATIVE', difficulty = 'MEDIUM' WHERE id = 6;
UPDATE questions SET evidence = 'LEVEL 4 / STAGE 1 / PRIVATE ARTIFACT A: output symbols repeat at offsets 1, 3, 1, 3.', instructions = 'Use the teammate ordering evidence to identify the transformation family and submit the shared key label.', puzzle_context = 'STAGE 1', expected_answer_hash = 'KEY-D', answer_type = 'TEXT', technical_category = 'COOPERATIVE', difficulty = 'MEDIUM' WHERE id = 7;
UPDATE questions SET evidence = 'LEVEL 4 / STAGE 1 / PRIVATE ARTIFACT B: candidate orderings produce one stable symbol sequence.', instructions = 'Use this ordering evidence with the teammate artifact to identify the transformation family and submit the shared key label.', puzzle_context = 'STAGE 1', expected_answer_hash = 'KEY-D', answer_type = 'TEXT', technical_category = 'COOPERATIVE', difficulty = 'MEDIUM' WHERE id = 8;
UPDATE questions SET evidence = 'LEVEL 5 / STAGE 1 / PRIVATE ARTIFACT A: identifiers K2, K5, K8 share a timestamp window.', instructions = 'Compare the identifiers with the teammate timeline and submit the shared correlation label.', puzzle_context = 'STAGE 1', expected_answer_hash = 'CHAIN-E', answer_type = 'TEXT', technical_category = 'COOPERATIVE', difficulty = 'MEDIUM' WHERE id = 9;
UPDATE questions SET evidence = 'LEVEL 5 / STAGE 1 / PRIVATE ARTIFACT B: timeline windows W1, W3, W4 contain one matching identifier chain.', instructions = 'Compare the timeline with the teammate identifiers and submit the shared correlation label.', puzzle_context = 'STAGE 1', expected_answer_hash = 'CHAIN-E', answer_type = 'TEXT', technical_category = 'COOPERATIVE', difficulty = 'MEDIUM' WHERE id = 10;
UPDATE questions SET evidence = 'LEVEL 6 / STAGE 1 / PRIVATE ARTIFACT A: constraint set permits sequence positions 1 and 3 but not 2.', instructions = 'Combine this constraint set with the teammate artifact and submit the shared protocol label.', puzzle_context = 'STAGE 1', expected_answer_hash = 'SET-F', answer_type = 'TEXT', technical_category = 'COOPERATIVE', difficulty = 'MEDIUM' WHERE id = 11;
UPDATE questions SET evidence = 'LEVEL 6 / STAGE 1 / PRIVATE ARTIFACT B: constraint set permits positions 2 and 3 but not 1.', instructions = 'Combine this constraint set with the teammate artifact and submit the shared protocol label.', puzzle_context = 'STAGE 1', expected_answer_hash = 'SET-F', answer_type = 'TEXT', technical_category = 'COOPERATIVE', difficulty = 'MEDIUM' WHERE id = 12;

UPDATE hints SET hint_content = 'Compare the two private artifacts. Look for the relationship both artifacts can confirm without copying a raw value.' WHERE level_id IN (SELECT id FROM levels WHERE level_number BETWEEN 1 AND 6);

-- Stage 2 for every level. Both players receive different evidence and must submit the same derived discovery.
INSERT INTO questions (level_id, stage_number, player_number, evidence, instructions, puzzle_context, expected_answer_hash, answer_type, is_active, technical_category, difficulty)
SELECT l.id, 2, 'PLAYER_1', 'STAGE 2 / PRIVATE ARTIFACT A: observe the marked transitions and retain only entries referenced by the stage-1 discovery.', 'Correlate this artifact with the teammate artifact. Submit the shared discovery, not a value copied from this screen.', 'STAGE 2', CASE l.level_number WHEN 1 THEN 'ROUTE-4' WHEN 2 THEN 'PAIR-27' WHEN 3 THEN 'PATH-C' WHEN 4 THEN 'ORDER-2' WHEN 5 THEN 'LINK-B' ELSE 'CORE-3' END, 'TEXT', true, 'COOPERATIVE', 'MEDIUM'
FROM levels l WHERE l.level_number BETWEEN 1 AND 6;

INSERT INTO questions (level_id, stage_number, player_number, evidence, instructions, puzzle_context, expected_answer_hash, answer_type, is_active, technical_category, difficulty)
SELECT l.id, 2, 'PLAYER_2', 'STAGE 2 / PRIVATE ARTIFACT B: use the relationship table to interpret the transitions selected by the teammate artifact.', 'Correlate this artifact with the teammate artifact. Submit the shared discovery, not a value copied from this screen.', 'STAGE 2', CASE l.level_number WHEN 1 THEN 'ROUTE-4' WHEN 2 THEN 'PAIR-27' WHEN 3 THEN 'PATH-C' WHEN 4 THEN 'ORDER-2' WHEN 5 THEN 'LINK-B' ELSE 'CORE-3' END, 'TEXT', true, 'COOPERATIVE', 'MEDIUM'
FROM levels l WHERE l.level_number BETWEEN 1 AND 6;

-- Stage 3 is present only for Levels 3, 5, and 6.
INSERT INTO questions (level_id, stage_number, player_number, evidence, instructions, puzzle_context, expected_answer_hash, answer_type, is_active, technical_category, difficulty)
SELECT l.id, 3, 'PLAYER_1', 'STAGE 3 / PRIVATE ARTIFACT A: reconstruct the final fragment using the stage-2 relationship.', 'Compare both fragments, apply the already discovered rule, and submit the single shared result.', 'STAGE 3', CASE l.level_number WHEN 3 THEN 'PACKET-9' WHEN 5 THEN 'CHAIN-6' ELSE 'FINAL-8' END, 'TEXT', true, 'COOPERATIVE', 'MEDIUM'
FROM levels l WHERE l.level_number IN (3, 5, 6);

INSERT INTO questions (level_id, stage_number, player_number, evidence, instructions, puzzle_context, expected_answer_hash, answer_type, is_active, technical_category, difficulty)
SELECT l.id, 3, 'PLAYER_2', 'STAGE 3 / PRIVATE ARTIFACT B: verify the ordering constraint and remove the decoy fragment.', 'Compare both fragments, apply the already discovered rule, and submit the single shared result.', 'STAGE 3', CASE l.level_number WHEN 3 THEN 'PACKET-9' WHEN 5 THEN 'CHAIN-6' ELSE 'FINAL-8' END, 'TEXT', true, 'COOPERATIVE', 'MEDIUM'
FROM levels l WHERE l.level_number IN (3, 5, 6);