-- Production-neutral content: the artifacts are technical and story-independent.
-- Each stage gives different evidence to each player, but both must submit the same derived discovery.

UPDATE levels SET name = 'SYSTEM RECONSTRUCTION', description = 'Reconstruct a system event chain from asymmetric logs and component relationships.' WHERE level_number = 1;
UPDATE levels SET name = 'DATA VAULT', description = 'Reassemble fragmented data and identify the transformation that makes it readable.' WHERE level_number = 2;
UPDATE levels SET name = 'NETWORK INCIDENT', description = 'Reconstruct a route, isolate suspicious traffic, and recover a damaged packet.' WHERE level_number = 3;
UPDATE levels SET name = 'ENCRYPTED ROOM', description = 'Infer a transformation from behavior, ordering, and reset evidence.' WHERE level_number = 4;
UPDATE levels SET name = 'COLLAPSED SYSTEM', description = 'Correlate forensic artifacts, follow an evidence chain, and extract a hidden pattern.' WHERE level_number = 5;
UPDATE levels SET name = 'THE CORE', description = 'Combine the mechanisms learned across the game into a final protocol.' WHERE level_number = 6;

UPDATE questions SET
 evidence = 'LOG STREAM A: 08:14:02 process=relay status=READY; 08:14:11 process=watcher status=REJECTED; 08:14:19 process=relay status=RETRY; 08:14:27 process=archive status=READ.\nLOG STREAM B: 08:13:58 process=archive status=READ; 08:14:11 process=watcher status=REJECTED.\nDECOY: 09:02:44 process=backup status=COMPLETE.',
 instructions = 'Sort the records by timestamp. Ignore the later maintenance event. The abnormal chain is the process that changes state twice. Submit the trace label you derive with your teammate.',
 puzzle_context = 'LEVEL 1 / STAGE 1: LOG COLLISION',
 expected_answer_hash = 'SYSTEM TRACE: K-17', answer_type = 'TEXT', technical_category = 'SEQUENCING', difficulty = 'MEDIUM',
 validation_rules = 'NORMALIZED_TEXT_EXACT', puzzle_metadata = '{"interaction":"timeline","discovery":"SYSTEM TRACE: K-17","decoys":["backup"]}'
WHERE level_id = (SELECT id FROM levels WHERE level_number = 1) AND stage_number = 1 AND player_number = 'PLAYER_1';

UPDATE questions SET
 evidence = 'COMPONENT MAP: relay owns channel K; watcher observes channel K; archive stores channel R.\nRELATIONSHIPS: a retry remains on the same channel; a rejected watcher event does not change ownership.\nDECOY: backup is attached to channel R.',
 instructions = 'Use the event chain from Player 1 and this component map. Identify the abnormal chain label, not the process name. Submit the shared discovery.',
 puzzle_context = 'LEVEL 1 / STAGE 1: LOG COLLISION',
 expected_answer_hash = 'SYSTEM TRACE: K-17', answer_type = 'TEXT', technical_category = 'CORRELATION', difficulty = 'MEDIUM',
 validation_rules = 'NORMALIZED_TEXT_EXACT', puzzle_metadata = '{"interaction":"component-map","discovery":"SYSTEM TRACE: K-17","decoys":["backup"]}'
WHERE level_id = (SELECT id FROM levels WHERE level_number = 1) AND stage_number = 1 AND player_number = 'PLAYER_2';

UPDATE questions SET evidence = 'ACCESS PANEL: node choices N-2, N-4, N-7. Process choices relay, watcher, archive. Sequence choices K-17, R-03, M-22. The panel accepts the node that owns the abnormal channel, the process that retried, and the trace label.', instructions = 'Use SYSTEM TRACE: K-17 and the component relationship from Stage 1. Select the node, process, and sequence in that order, then submit the recovery fragment.', puzzle_context = 'LEVEL 1 / STAGE 2: ACCESS PANEL', expected_answer_hash = 'RECOVERY FRAGMENT 01', answer_type = 'TEXT', technical_category = 'SYSTEMS', difficulty = 'MEDIUM', validation_rules = 'NORMALIZED_TEXT_EXACT', puzzle_metadata = '{"interaction":"access-panel","choices":["N-2","N-4","N-7","relay","watcher","archive","K-17","R-03","M-22"],"discovery":"RECOVERY FRAGMENT 01"}' WHERE level_id = (SELECT id FROM levels WHERE level_number = 1) AND stage_number = 2 AND player_number = 'PLAYER_1';
UPDATE questions SET evidence = 'ACCESS PANEL MIRROR: the node is selected by channel ownership; the process is selected by the state change; the sequence is selected by the trace label. Node N-4 owns channel K, relay performed the retry, and K-17 is the trace.', instructions = 'Confirm the three-part selection with your teammate. Submit RECOVERY FRAGMENT 01 after both consoles agree.', puzzle_context = 'LEVEL 1 / STAGE 2: ACCESS PANEL', expected_answer_hash = 'RECOVERY FRAGMENT 01', answer_type = 'TEXT', technical_category = 'SYSTEMS', difficulty = 'MEDIUM', validation_rules = 'NORMALIZED_TEXT_EXACT', puzzle_metadata = '{"interaction":"access-panel","discovery":"RECOVERY FRAGMENT 01"}' WHERE level_id = (SELECT id FROM levels WHERE level_number = 1) AND stage_number = 2 AND player_number = 'PLAYER_2';

UPDATE questions SET evidence = 'FRAGMENT VAULT A: [B7] ends with marker 2F; [41] begins with marker 7B; [C3] is followed by a checksum marker. The vault also contains decoy [99] with no matching boundary.', instructions = 'Match boundaries with the teammate fragment set. Order the legitimate fragments, identify the representation, and submit the transformation discovery.', puzzle_context = 'LEVEL 2 / STAGE 1: FRAGMENT VAULT', expected_answer_hash = 'HEX-TO-TEXT', answer_type = 'TEXT', technical_category = 'DATA-RECONSTRUCTION', difficulty = 'MEDIUM', validation_rules = 'NORMALIZED_TEXT_EXACT', puzzle_metadata = '{"interaction":"fragment-assembly","discovery":"HEX-TO-TEXT","decoy":"99"}' WHERE level_id = (SELECT id FROM levels WHERE level_number = 2) AND stage_number = 1 AND player_number = 'PLAYER_1';
UPDATE questions SET evidence = 'FRAGMENT VAULT B: boundary order is C3 -> B7 -> 41; the checksum marker appears only after the third fragment. Decoy [D0] has a valid-looking byte but no boundary partner.', instructions = 'Use the boundary order and your teammate evidence to identify which representation the recovered bytes use. Submit the shared transformation discovery.', puzzle_context = 'LEVEL 2 / STAGE 1: FRAGMENT VAULT', expected_answer_hash = 'HEX-TO-TEXT', answer_type = 'TEXT', technical_category = 'DATA-RECONSTRUCTION', difficulty = 'MEDIUM', validation_rules = 'NORMALIZED_TEXT_EXACT', puzzle_metadata = '{"interaction":"fragment-assembly","discovery":"HEX-TO-TEXT","decoy":"D0"}' WHERE level_id = (SELECT id FROM levels WHERE level_number = 2) AND stage_number = 1 AND player_number = 'PLAYER_2';
UPDATE questions SET evidence = 'TRANSFORMATION CHAMBER: recovered bytes are 52 45 43 4F 56 45 52 59. Operations offered: decimal-to-text, hex-to-text, reverse bytes, and base64 decode.', instructions = 'Select the operation discovered in Stage 1, process the assembled bytes, and submit the recovered fragment.', puzzle_context = 'LEVEL 2 / STAGE 2: TRANSFORMATION CHAMBER', expected_answer_hash = 'RECOVERY FRAGMENT 02', answer_type = 'TEXT', technical_category = 'TRANSFORMATION', difficulty = 'MEDIUM', validation_rules = 'NORMALIZED_TEXT_EXACT', puzzle_metadata = '{"interaction":"transformation","operations":["decimal-to-text","hex-to-text","reverse-bytes","base64-decode"],"discovery":"RECOVERY FRAGMENT 02"}' WHERE level_id = (SELECT id FROM levels WHERE level_number = 2) AND stage_number = 2 AND player_number = 'PLAYER_1';
UPDATE questions SET evidence = 'TRANSFORMATION CHAMBER CHECK: hex pairs map to readable ASCII only when interpreted left-to-right. The first four decoded characters are R-E-C-O.', instructions = 'Verify the operation and order with your teammate. Submit RECOVERY FRAGMENT 02 only after the output is readable.', puzzle_context = 'LEVEL 2 / STAGE 2: TRANSFORMATION CHAMBER', expected_answer_hash = 'RECOVERY FRAGMENT 02', answer_type = 'TEXT', technical_category = 'TRANSFORMATION', difficulty = 'MEDIUM', validation_rules = 'NORMALIZED_TEXT_EXACT', puzzle_metadata = '{"interaction":"transformation","discovery":"RECOVERY FRAGMENT 02"}' WHERE level_id = (SELECT id FROM levels WHERE level_number = 2) AND stage_number = 2 AND player_number = 'PLAYER_2';

UPDATE questions SET evidence = 'TOPOLOGY FRAGMENT A: confirmed edges are A-B and B-C. Candidate edges are A-D, C-D, and B-D. The incident source is attached to A.', instructions = 'Build the topology with your teammate. Keep only edges confirmed by both evidence sets and submit the route label.', puzzle_context = 'LEVEL 3 / STAGE 1: NETWORK RECONSTRUCTION', expected_answer_hash = 'ROUTE A-B-C', answer_type = 'TEXT', technical_category = 'NETWORK-RECONSTRUCTION', difficulty = 'MEDIUM', validation_rules = 'NORMALIZED_TEXT_EXACT', puzzle_metadata = '{"interaction":"network-graph","discovery":"ROUTE A-B-C"}' WHERE level_id = (SELECT id FROM levels WHERE level_number = 3) AND stage_number = 1 AND player_number = 'PLAYER_1';
UPDATE questions SET evidence = 'TOPOLOGY FRAGMENT B: confirmed edges are B-C and C-E. Candidate edges are A-E, A-D, and B-D. The incident destination is attached to E.', instructions = 'Build the topology with your teammate. The valid path must connect the source and destination using only mutually confirmed edges. Submit the route label.', puzzle_context = 'LEVEL 3 / STAGE 1: NETWORK RECONSTRUCTION', expected_answer_hash = 'ROUTE A-B-C', answer_type = 'TEXT', technical_category = 'NETWORK-RECONSTRUCTION', difficulty = 'MEDIUM', validation_rules = 'NORMALIZED_TEXT_EXACT', puzzle_metadata = '{"interaction":"network-graph","discovery":"ROUTE A-B-C"}' WHERE level_id = (SELECT id FROM levels WHERE level_number = 3) AND stage_number = 1 AND player_number = 'PLAYER_2';
UPDATE questions SET evidence = 'TRACE TABLE A: 10:02:01 A->B CONNECT; 10:02:03 B->C FORWARD; 10:02:04 C->E FORWARD; 10:02:09 A->D DROP. Legitimate traffic follows the reconstructed route.', instructions = 'Order the events and isolate the suspicious connection. Submit PACKET PATH C-E after comparing with the teammate trace.', puzzle_context = 'LEVEL 3 / STAGE 2: TRACE THE CONNECTION', expected_answer_hash = 'PACKET PATH C-E', answer_type = 'TEXT', technical_category = 'NETWORK-FORENSICS', difficulty = 'MEDIUM', validation_rules = 'NORMALIZED_TEXT_EXACT', puzzle_metadata = '{"interaction":"trace-timeline","discovery":"PACKET PATH C-E"}' WHERE level_id = (SELECT id FROM levels WHERE level_number = 3) AND stage_number = 2 AND player_number = 'PLAYER_1';
UPDATE questions SET evidence = 'TRACE TABLE B: 10:02:03 B->C FORWARD; 10:02:04 C->E FORWARD contains an unexpected payload marker; 10:02:09 A->D DROP is decoy traffic.', instructions = 'Compare timestamps, direction, and payload marker with the teammate trace. Submit PACKET PATH C-E.', puzzle_context = 'LEVEL 3 / STAGE 2: TRACE THE CONNECTION', expected_answer_hash = 'PACKET PATH C-E', answer_type = 'TEXT', technical_category = 'NETWORK-FORENSICS', difficulty = 'MEDIUM', validation_rules = 'NORMALIZED_TEXT_EXACT', puzzle_metadata = '{"interaction":"trace-timeline","discovery":"PACKET PATH C-E"}' WHERE level_id = (SELECT id FROM levels WHERE level_number = 3) AND stage_number = 2 AND player_number = 'PLAYER_2';
UPDATE questions SET evidence = 'PACKET FRAGMENT A: header bytes 50 4B; payload fragments 52 45 and 43 4F; checksum marker is 56 45 52 59.', instructions = 'Order the packet fragments using the route and trace discoveries. Process the bytes and submit RECOVERY FRAGMENT 03.', puzzle_context = 'LEVEL 3 / STAGE 3: PACKET RECOVERY', expected_answer_hash = 'RECOVERY FRAGMENT 03', answer_type = 'TEXT', technical_category = 'PACKET-RECOVERY', difficulty = 'MEDIUM', validation_rules = 'NORMALIZED_TEXT_EXACT', puzzle_metadata = '{"interaction":"packet-reassembly","discovery":"RECOVERY FRAGMENT 03"}' WHERE level_id = (SELECT id FROM levels WHERE level_number = 3) AND stage_number = 3 AND player_number = 'PLAYER_1';
UPDATE questions SET evidence = 'PACKET FRAGMENT B: the valid payload order is header, payload, checksum. The route label selects the C-E fragment and excludes the dropped A-D fragment.', instructions = 'Use the route and trace discoveries to select the valid packet fragment. Submit RECOVERY FRAGMENT 03.', puzzle_context = 'LEVEL 3 / STAGE 3: PACKET RECOVERY', expected_answer_hash = 'RECOVERY FRAGMENT 03', answer_type = 'TEXT', technical_category = 'PACKET-RECOVERY', difficulty = 'MEDIUM', validation_rules = 'NORMALIZED_TEXT_EXACT', puzzle_metadata = '{"interaction":"packet-reassembly","discovery":"RECOVERY FRAGMENT 03"}' WHERE level_id = (SELECT id FROM levels WHERE level_number = 3) AND stage_number = 3 AND player_number = 'PLAYER_2';

UPDATE questions SET evidence = 'CIPHER BEHAVIOR A: symbol pairs preserve distance; repeated input symbols produce repeated output symbols; the first observed pair is A->D and B->E.', instructions = 'Infer the transformation family from behavior. Compare the key characteristics with your teammate and submit the shared transformation label.', puzzle_context = 'LEVEL 4 / STAGE 1: CIPHER DISCOVERY', expected_answer_hash = 'SHIFT-3', answer_type = 'TEXT', technical_category = 'CIPHER-REASONING', difficulty = 'MEDIUM', validation_rules = 'NORMALIZED_TEXT_EXACT', puzzle_metadata = '{"interaction":"cipher-deduction","discovery":"SHIFT-3"}' WHERE level_id = (SELECT id FROM levels WHERE level_number = 4) AND stage_number = 1 AND player_number = 'PLAYER_1';
UPDATE questions SET evidence = 'CIPHER CONTEXT B: the symbol sequence resets at each fragment boundary; ordering fragments 2-1-3 makes the repeated marker align. A three-position shift preserves the observed reset behavior.', instructions = 'Use ordering and reset behavior with the teammate symbol evidence. Submit SHIFT-3.', puzzle_context = 'LEVEL 4 / STAGE 1: CIPHER DISCOVERY', expected_answer_hash = 'SHIFT-3', answer_type = 'TEXT', technical_category = 'CIPHER-REASONING', difficulty = 'MEDIUM', validation_rules = 'NORMALIZED_TEXT_EXACT', puzzle_metadata = '{"interaction":"cipher-deduction","discovery":"SHIFT-3"}' WHERE level_id = (SELECT id FROM levels WHERE level_number = 4) AND stage_number = 1 AND player_number = 'PLAYER_2';
UPDATE questions SET evidence = 'DECRYPTION INTERFACE A: fragments are [KHOOR], [ZRUOG]. Candidate transforms: shift 1, shift 3, reverse, substitution. Fragment order is selectable.', instructions = 'Select the discovered transformation, arrange the fragments, and verify the readable result with your teammate. Submit RECOVERY FRAGMENT 04.', puzzle_context = 'LEVEL 4 / STAGE 2: DECRYPTION INTERFACE', expected_answer_hash = 'RECOVERY FRAGMENT 04', answer_type = 'TEXT', technical_category = 'DECRYPTION', difficulty = 'MEDIUM', validation_rules = 'NORMALIZED_TEXT_EXACT', puzzle_metadata = '{"interaction":"decryption","operations":["shift-1","shift-3","reverse","substitution"],"discovery":"RECOVERY FRAGMENT 04"}' WHERE level_id = (SELECT id FROM levels WHERE level_number = 4) AND stage_number = 2 AND player_number = 'PLAYER_1';
UPDATE questions SET evidence = 'DECRYPTION INTERFACE B: the correct order is fragment 1 then fragment 2; applying shift 3 converts KHOOR ZRUOG into a readable two-word result.', instructions = 'Confirm the transform and order. Submit RECOVERY FRAGMENT 04 after both players verify the output.', puzzle_context = 'LEVEL 4 / STAGE 2: DECRYPTION INTERFACE', expected_answer_hash = 'RECOVERY FRAGMENT 04', answer_type = 'TEXT', technical_category = 'DECRYPTION', difficulty = 'MEDIUM', validation_rules = 'NORMALIZED_TEXT_EXACT', puzzle_metadata = '{"interaction":"decryption","discovery":"RECOVERY FRAGMENT 04"}' WHERE level_id = (SELECT id FROM levels WHERE level_number = 4) AND stage_number = 2 AND player_number = 'PLAYER_2';

UPDATE questions SET evidence = 'EVIDENCE BOARD A: file F-12 modified at 14:03; identifier R-4 appears at 14:04; network event N-9 references R-4. Decoys: F-88 and N-2.', instructions = 'Connect only artifacts that share the same incident window and identifier. Compare with the teammate board and submit the incident chain label.', puzzle_context = 'LEVEL 5 / STAGE 1: EVIDENCE BOARD', expected_answer_hash = 'CHAIN F-12/R-4/N-9', answer_type = 'TEXT', technical_category = 'FORENSICS', difficulty = 'HARD', validation_rules = 'NORMALIZED_TEXT_EXACT', puzzle_metadata = '{"interaction":"evidence-board","discovery":"CHAIN F-12/R-4/N-9"}' WHERE level_id = (SELECT id FROM levels WHERE level_number = 5) AND stage_number = 1 AND player_number = 'PLAYER_1';
UPDATE questions SET evidence = 'EVIDENCE BOARD B: identifier R-4 is read by process P-7 at 14:04; network event N-9 begins at 14:05; decoy process P-2 references R-8.', instructions = 'Connect only artifacts that share the same incident window and identifier. Compare with the teammate board and submit the incident chain label.', puzzle_context = 'LEVEL 5 / STAGE 1: EVIDENCE BOARD', expected_answer_hash = 'CHAIN F-12/R-4/N-9', answer_type = 'TEXT', technical_category = 'FORENSICS', difficulty = 'HARD', validation_rules = 'NORMALIZED_TEXT_EXACT', puzzle_metadata = '{"interaction":"evidence-board","discovery":"CHAIN F-12/R-4/N-9"}' WHERE level_id = (SELECT id FROM levels WHERE level_number = 5) AND stage_number = 1 AND player_number = 'PLAYER_2';
UPDATE questions SET evidence = 'CHAIN FOLLOW-UP A: the linked file points to transform record T-3; T-3 references the recovery fragment from Level 2. The unrelated record T-8 has no shared identifier.', instructions = 'Follow the validated evidence chain and use the earlier transformation discovery. Submit CHAIN VERIFIED.', puzzle_context = 'LEVEL 5 / STAGE 2: EVIDENCE CHAIN', expected_answer_hash = 'CHAIN VERIFIED', answer_type = 'TEXT', technical_category = 'FORENSICS', difficulty = 'HARD', validation_rules = 'NORMALIZED_TEXT_EXACT', puzzle_metadata = '{"interaction":"evidence-chain","discovery":"CHAIN VERIFIED"}' WHERE level_id = (SELECT id FROM levels WHERE level_number = 5) AND stage_number = 2 AND player_number = 'PLAYER_1';
UPDATE questions SET evidence = 'CHAIN FOLLOW-UP B: T-3 is the only record whose output marker matches RECOVERY FRAGMENT 02; T-8 has a different marker. The next node is N-9 from Stage 1.', instructions = 'Follow the validated evidence chain and use the earlier transformation discovery. Submit CHAIN VERIFIED.', puzzle_context = 'LEVEL 5 / STAGE 2: EVIDENCE CHAIN', expected_answer_hash = 'CHAIN VERIFIED', answer_type = 'TEXT', technical_category = 'FORENSICS', difficulty = 'HARD', validation_rules = 'NORMALIZED_TEXT_EXACT', puzzle_metadata = '{"interaction":"evidence-chain","discovery":"CHAIN VERIFIED"}' WHERE level_id = (SELECT id FROM levels WHERE level_number = 5) AND stage_number = 2 AND player_number = 'PLAYER_2';
UPDATE questions SET evidence = 'PATTERN A: selected positions are 2, 4, 6, 8. The first half contains the index rule; the second half contains the visible markers.', instructions = 'Combine the index rule with the teammate markers. Extract the ordered result and submit RECOVERY FRAGMENT 05.', puzzle_context = 'LEVEL 5 / STAGE 3: PATTERN EXTRACTION', expected_answer_hash = 'RECOVERY FRAGMENT 05', answer_type = 'TEXT', technical_category = 'PATTERN-RECOGNITION', difficulty = 'HARD', validation_rules = 'NORMALIZED_TEXT_EXACT', puzzle_metadata = '{"interaction":"pattern-extraction","discovery":"RECOVERY FRAGMENT 05"}' WHERE level_id = (SELECT id FROM levels WHERE level_number = 5) AND stage_number = 3 AND player_number = 'PLAYER_1';
UPDATE questions SET evidence = 'PATTERN B: markers at positions 2, 4, 6, 8 read in order only after the chain is filtered to R-4 and T-3. Odd positions are decoys.', instructions = 'Combine the index rule with the teammate markers. Extract the ordered result and submit RECOVERY FRAGMENT 05.', puzzle_context = 'LEVEL 5 / STAGE 3: PATTERN EXTRACTION', expected_answer_hash = 'RECOVERY FRAGMENT 05', answer_type = 'TEXT', technical_category = 'PATTERN-RECOGNITION', difficulty = 'HARD', validation_rules = 'NORMALIZED_TEXT_EXACT', puzzle_metadata = '{"interaction":"pattern-extraction","discovery":"RECOVERY FRAGMENT 05"}' WHERE level_id = (SELECT id FROM levels WHERE level_number = 5) AND stage_number = 3 AND player_number = 'PLAYER_2';

UPDATE questions SET evidence = 'CORE KEY A: the access sequence must begin with the system trace discovery, then use the network route, then the transformation discovery. The remaining positions are locked.', instructions = 'Combine this ordering constraint with the teammate key. Use the Core access controls and submit CORE ACCESS GRANTED.', puzzle_context = 'LEVEL 6 / STAGE 1: DUAL KEY', expected_answer_hash = 'CORE ACCESS GRANTED', answer_type = 'TEXT', technical_category = 'PROTOCOL-RECONSTRUCTION', difficulty = 'HARD', validation_rules = 'NORMALIZED_TEXT_EXACT', puzzle_metadata = '{"interaction":"dual-key","discovery":"CORE ACCESS GRANTED"}' WHERE level_id = (SELECT id FROM levels WHERE level_number = 6) AND stage_number = 1 AND player_number = 'PLAYER_1';
UPDATE questions SET evidence = 'CORE KEY B: the final two positions must be filled by the pattern fragment and the packet fragment; the data transformation fragment verifies the middle boundary.', instructions = 'Combine this ordering constraint with the teammate key. Use the Core access controls and submit CORE ACCESS GRANTED.', puzzle_context = 'LEVEL 6 / STAGE 1: DUAL KEY', expected_answer_hash = 'CORE ACCESS GRANTED', answer_type = 'TEXT', technical_category = 'PROTOCOL-RECONSTRUCTION', difficulty = 'HARD', validation_rules = 'NORMALIZED_TEXT_EXACT', puzzle_metadata = '{"interaction":"dual-key","discovery":"CORE ACCESS GRANTED"}' WHERE level_id = (SELECT id FROM levels WHERE level_number = 6) AND stage_number = 1 AND player_number = 'PLAYER_2';
UPDATE questions SET evidence = 'CORE RECONSTRUCTION A: arrange six recovered fragments by dependency: the trace establishes the route, the route selects the packet, the packet confirms the transform, the transform verifies the cipher, the cipher selects the chain, and the chain exposes the pattern.', instructions = 'Reconstruct the six-step dependency protocol with your teammate. Submit CORE SEQUENCE VERIFIED.', puzzle_context = 'LEVEL 6 / STAGE 2: CORE RECONSTRUCTION', expected_answer_hash = 'CORE SEQUENCE VERIFIED', answer_type = 'TEXT', technical_category = 'PROTOCOL-RECONSTRUCTION', difficulty = 'HARD', validation_rules = 'NORMALIZED_TEXT_EXACT', puzzle_metadata = '{"interaction":"sequence-reconstruction","discovery":"CORE SEQUENCE VERIFIED"}' WHERE level_id = (SELECT id FROM levels WHERE level_number = 6) AND stage_number = 2 AND player_number = 'PLAYER_1';
UPDATE questions SET evidence = 'CORE RECONSTRUCTION B: a fragment cannot precede the discovery that makes it interpretable. The six dependency edges are trace->route, route->packet, packet->transform, transform->cipher, cipher->chain, chain->pattern.', instructions = 'Reconstruct the six-step dependency protocol with your teammate. Submit CORE SEQUENCE VERIFIED.', puzzle_context = 'LEVEL 6 / STAGE 2: CORE RECONSTRUCTION', expected_answer_hash = 'CORE SEQUENCE VERIFIED', answer_type = 'TEXT', technical_category = 'PROTOCOL-RECONSTRUCTION', difficulty = 'HARD', validation_rules = 'NORMALIZED_TEXT_EXACT', puzzle_metadata = '{"interaction":"sequence-reconstruction","discovery":"CORE SEQUENCE VERIFIED"}' WHERE level_id = (SELECT id FROM levels WHERE level_number = 6) AND stage_number = 2 AND player_number = 'PLAYER_2';
UPDATE questions SET evidence = 'FINAL PROTOCOL A: the six recovered fragments provide six ordered positions. Your console contains positions 1, 3, and 5; the teammate console contains positions 2, 4, and 6. Use the protocol order, not a raw copied value.', instructions = 'Derive the six-digit passkey from the complete final protocol and submit FINAL PROTOCOL VERIFIED. The passkey itself is never sent to either client.', puzzle_context = 'LEVEL 6 / STAGE 3: FINAL PROTOCOL', expected_answer_hash = 'FINAL PROTOCOL VERIFIED', answer_type = 'TEXT', technical_category = 'FINAL-PROTOCOL', difficulty = 'HARD', validation_rules = 'NORMALIZED_TEXT_EXACT', puzzle_metadata = '{"interaction":"final-protocol","discovery":"FINAL PROTOCOL VERIFIED"}' WHERE level_id = (SELECT id FROM levels WHERE level_number = 6) AND stage_number = 3 AND player_number = 'PLAYER_1';
UPDATE questions SET evidence = 'FINAL PROTOCOL B: the six positions must be cross-checked against the dependency order and the two-player evidence. No single console contains enough positions to derive the result.', instructions = 'Derive the six-digit passkey from the complete final protocol and submit FINAL PROTOCOL VERIFIED. The passkey itself is never sent to either client.', puzzle_context = 'LEVEL 6 / STAGE 3: FINAL PROTOCOL', expected_answer_hash = 'FINAL PROTOCOL VERIFIED', answer_type = 'TEXT', technical_category = 'FINAL-PROTOCOL', difficulty = 'HARD', validation_rules = 'NORMALIZED_TEXT_EXACT', puzzle_metadata = '{"interaction":"final-protocol","discovery":"FINAL PROTOCOL VERIFIED"}' WHERE level_id = (SELECT id FROM levels WHERE level_number = 6) AND stage_number = 3 AND player_number = 'PLAYER_2';
