-- V53: Configure official competition teams and purge all other login credentials
-- Preserves ONLY:
-- 1. TEAM-ALPHA
-- 2. TEAM-BETA
-- 3. TEAM-2NDPLACE
-- 4. TEAM-BDUCODERS
-- 5. TEAM-CTRL+ESC
-- 6. TEAM-CYBERTRONS
-- 7. TEAM-DOJISDOMAIN
-- 8. TEAM-DUOSEEKERS
-- 9. TEAM-GAC_WARRIORS
-- 10. TEAM-GAMMA
-- 11. TEAM-INEVITABLE
-- 12. TEAM-JAMALIANS
-- 13. TEAM-LAZYCODERS
-- 14. TEAM-NINETEEN
-- 15. TEAM-POWERHITTERS
-- 16. TEAM-PHOENIX
-- 17. TEAM-REZERO
-- 18. TEAM-UNKNOWN
-- 19. TEAM-CHAIFLOW
-- 20. TEAM-VARISHU

-- 1. Terminate all active sessions
UPDATE game_sessions
SET status = 'TERMINATED',
    is_connected = FALSE,
    disconnected_at = CURRENT_TIMESTAMP
WHERE status = 'ACTIVE' OR is_connected = TRUE;

-- 2. Remove all progression and session data for teams NOT in the official list
DELETE FROM answer_attempts WHERE team_id IN (
    SELECT id FROM teams WHERE team_code NOT IN (
        'TEAM-ALPHA', 'TEAM-BETA', 'TEAM-2NDPLACE', 'TEAM-BDUCODERS', 'TEAM-CTRL+ESC',
        'TEAM-CYBERTRONS', 'TEAM-DOJISDOMAIN', 'TEAM-DUOSEEKERS', 'TEAM-GAC_WARRIORS',
        'TEAM-GAMMA', 'TEAM-INEVITABLE', 'TEAM-JAMALIANS', 'TEAM-LAZYCODERS',
        'TEAM-NINETEEN', 'TEAM-POWERHITTERS', 'TEAM-PHOENIX', 'TEAM-REZERO',
        'TEAM-UNKNOWN', 'TEAM-CHAIFLOW', 'TEAM-VARISHU'
    )
);

DELETE FROM discovery_submissions WHERE team_id IN (
    SELECT id FROM teams WHERE team_code NOT IN (
        'TEAM-ALPHA', 'TEAM-BETA', 'TEAM-2NDPLACE', 'TEAM-BDUCODERS', 'TEAM-CTRL+ESC',
        'TEAM-CYBERTRONS', 'TEAM-DOJISDOMAIN', 'TEAM-DUOSEEKERS', 'TEAM-GAC_WARRIORS',
        'TEAM-GAMMA', 'TEAM-INEVITABLE', 'TEAM-JAMALIANS', 'TEAM-LAZYCODERS',
        'TEAM-NINETEEN', 'TEAM-POWERHITTERS', 'TEAM-PHOENIX', 'TEAM-REZERO',
        'TEAM-UNKNOWN', 'TEAM-CHAIFLOW', 'TEAM-VARISHU'
    )
);

DELETE FROM team_stage_progress WHERE team_id IN (
    SELECT id FROM teams WHERE team_code NOT IN (
        'TEAM-ALPHA', 'TEAM-BETA', 'TEAM-2NDPLACE', 'TEAM-BDUCODERS', 'TEAM-CTRL+ESC',
        'TEAM-CYBERTRONS', 'TEAM-DOJISDOMAIN', 'TEAM-DUOSEEKERS', 'TEAM-GAC_WARRIORS',
        'TEAM-GAMMA', 'TEAM-INEVITABLE', 'TEAM-JAMALIANS', 'TEAM-LAZYCODERS',
        'TEAM-NINETEEN', 'TEAM-POWERHITTERS', 'TEAM-PHOENIX', 'TEAM-REZERO',
        'TEAM-UNKNOWN', 'TEAM-CHAIFLOW', 'TEAM-VARISHU'
    )
);

DELETE FROM team_level_progress WHERE team_id IN (
    SELECT id FROM teams WHERE team_code NOT IN (
        'TEAM-ALPHA', 'TEAM-BETA', 'TEAM-2NDPLACE', 'TEAM-BDUCODERS', 'TEAM-CTRL+ESC',
        'TEAM-CYBERTRONS', 'TEAM-DOJISDOMAIN', 'TEAM-DUOSEEKERS', 'TEAM-GAC_WARRIORS',
        'TEAM-GAMMA', 'TEAM-INEVITABLE', 'TEAM-JAMALIANS', 'TEAM-LAZYCODERS',
        'TEAM-NINETEEN', 'TEAM-POWERHITTERS', 'TEAM-PHOENIX', 'TEAM-REZERO',
        'TEAM-UNKNOWN', 'TEAM-CHAIFLOW', 'TEAM-VARISHU'
    )
);

DELETE FROM team_riddle_progress WHERE team_id IN (
    SELECT id FROM teams WHERE team_code NOT IN (
        'TEAM-ALPHA', 'TEAM-BETA', 'TEAM-2NDPLACE', 'TEAM-BDUCODERS', 'TEAM-CTRL+ESC',
        'TEAM-CYBERTRONS', 'TEAM-DOJISDOMAIN', 'TEAM-DUOSEEKERS', 'TEAM-GAC_WARRIORS',
        'TEAM-GAMMA', 'TEAM-INEVITABLE', 'TEAM-JAMALIANS', 'TEAM-LAZYCODERS',
        'TEAM-NINETEEN', 'TEAM-POWERHITTERS', 'TEAM-PHOENIX', 'TEAM-REZERO',
        'TEAM-UNKNOWN', 'TEAM-CHAIFLOW', 'TEAM-VARISHU'
    )
);

DELETE FROM team_story_progress WHERE team_id IN (
    SELECT id FROM teams WHERE team_code NOT IN (
        'TEAM-ALPHA', 'TEAM-BETA', 'TEAM-2NDPLACE', 'TEAM-BDUCODERS', 'TEAM-CTRL+ESC',
        'TEAM-CYBERTRONS', 'TEAM-DOJISDOMAIN', 'TEAM-DUOSEEKERS', 'TEAM-GAC_WARRIORS',
        'TEAM-GAMMA', 'TEAM-INEVITABLE', 'TEAM-JAMALIANS', 'TEAM-LAZYCODERS',
        'TEAM-NINETEEN', 'TEAM-POWERHITTERS', 'TEAM-PHOENIX', 'TEAM-REZERO',
        'TEAM-UNKNOWN', 'TEAM-CHAIFLOW', 'TEAM-VARISHU'
    )
);

DELETE FROM hint_usage WHERE team_id IN (
    SELECT id FROM teams WHERE team_code NOT IN (
        'TEAM-ALPHA', 'TEAM-BETA', 'TEAM-2NDPLACE', 'TEAM-BDUCODERS', 'TEAM-CTRL+ESC',
        'TEAM-CYBERTRONS', 'TEAM-DOJISDOMAIN', 'TEAM-DUOSEEKERS', 'TEAM-GAC_WARRIORS',
        'TEAM-GAMMA', 'TEAM-INEVITABLE', 'TEAM-JAMALIANS', 'TEAM-LAZYCODERS',
        'TEAM-NINETEEN', 'TEAM-POWERHITTERS', 'TEAM-PHOENIX', 'TEAM-REZERO',
        'TEAM-UNKNOWN', 'TEAM-CHAIFLOW', 'TEAM-VARISHU'
    )
);

DELETE FROM anti_cheat_events WHERE team_id IN (
    SELECT id FROM teams WHERE team_code NOT IN (
        'TEAM-ALPHA', 'TEAM-BETA', 'TEAM-2NDPLACE', 'TEAM-BDUCODERS', 'TEAM-CTRL+ESC',
        'TEAM-CYBERTRONS', 'TEAM-DOJISDOMAIN', 'TEAM-DUOSEEKERS', 'TEAM-GAC_WARRIORS',
        'TEAM-GAMMA', 'TEAM-INEVITABLE', 'TEAM-JAMALIANS', 'TEAM-LAZYCODERS',
        'TEAM-NINETEEN', 'TEAM-POWERHITTERS', 'TEAM-PHOENIX', 'TEAM-REZERO',
        'TEAM-UNKNOWN', 'TEAM-CHAIFLOW', 'TEAM-VARISHU'
    )
);

DELETE FROM team_anti_cheat_summary WHERE team_id IN (
    SELECT id FROM teams WHERE team_code NOT IN (
        'TEAM-ALPHA', 'TEAM-BETA', 'TEAM-2NDPLACE', 'TEAM-BDUCODERS', 'TEAM-CTRL+ESC',
        'TEAM-CYBERTRONS', 'TEAM-DOJISDOMAIN', 'TEAM-DUOSEEKERS', 'TEAM-GAC_WARRIORS',
        'TEAM-GAMMA', 'TEAM-INEVITABLE', 'TEAM-JAMALIANS', 'TEAM-LAZYCODERS',
        'TEAM-NINETEEN', 'TEAM-POWERHITTERS', 'TEAM-PHOENIX', 'TEAM-REZERO',
        'TEAM-UNKNOWN', 'TEAM-CHAIFLOW', 'TEAM-VARISHU'
    )
);

DELETE FROM score_events WHERE team_id IN (
    SELECT id FROM teams WHERE team_code NOT IN (
        'TEAM-ALPHA', 'TEAM-BETA', 'TEAM-2NDPLACE', 'TEAM-BDUCODERS', 'TEAM-CTRL+ESC',
        'TEAM-CYBERTRONS', 'TEAM-DOJISDOMAIN', 'TEAM-DUOSEEKERS', 'TEAM-GAC_WARRIORS',
        'TEAM-GAMMA', 'TEAM-INEVITABLE', 'TEAM-JAMALIANS', 'TEAM-LAZYCODERS',
        'TEAM-NINETEEN', 'TEAM-POWERHITTERS', 'TEAM-PHOENIX', 'TEAM-REZERO',
        'TEAM-UNKNOWN', 'TEAM-CHAIFLOW', 'TEAM-VARISHU'
    )
);

DELETE FROM game_events WHERE team_id IN (
    SELECT id FROM teams WHERE team_code NOT IN (
        'TEAM-ALPHA', 'TEAM-BETA', 'TEAM-2NDPLACE', 'TEAM-BDUCODERS', 'TEAM-CTRL+ESC',
        'TEAM-CYBERTRONS', 'TEAM-DOJISDOMAIN', 'TEAM-DUOSEEKERS', 'TEAM-GAC_WARRIORS',
        'TEAM-GAMMA', 'TEAM-INEVITABLE', 'TEAM-JAMALIANS', 'TEAM-LAZYCODERS',
        'TEAM-NINETEEN', 'TEAM-POWERHITTERS', 'TEAM-PHOENIX', 'TEAM-REZERO',
        'TEAM-UNKNOWN', 'TEAM-CHAIFLOW', 'TEAM-VARISHU'
    )
);

DELETE FROM game_sessions WHERE team_id IN (
    SELECT id FROM teams WHERE team_code NOT IN (
        'TEAM-ALPHA', 'TEAM-BETA', 'TEAM-2NDPLACE', 'TEAM-BDUCODERS', 'TEAM-CTRL+ESC',
        'TEAM-CYBERTRONS', 'TEAM-DOJISDOMAIN', 'TEAM-DUOSEEKERS', 'TEAM-GAC_WARRIORS',
        'TEAM-GAMMA', 'TEAM-INEVITABLE', 'TEAM-JAMALIANS', 'TEAM-LAZYCODERS',
        'TEAM-NINETEEN', 'TEAM-POWERHITTERS', 'TEAM-PHOENIX', 'TEAM-REZERO',
        'TEAM-UNKNOWN', 'TEAM-CHAIFLOW', 'TEAM-VARISHU'
    )
);

DELETE FROM players WHERE team_id IN (
    SELECT id FROM teams WHERE team_code NOT IN (
        'TEAM-ALPHA', 'TEAM-BETA', 'TEAM-2NDPLACE', 'TEAM-BDUCODERS', 'TEAM-CTRL+ESC',
        'TEAM-CYBERTRONS', 'TEAM-DOJISDOMAIN', 'TEAM-DUOSEEKERS', 'TEAM-GAC_WARRIORS',
        'TEAM-GAMMA', 'TEAM-INEVITABLE', 'TEAM-JAMALIANS', 'TEAM-LAZYCODERS',
        'TEAM-NINETEEN', 'TEAM-POWERHITTERS', 'TEAM-PHOENIX', 'TEAM-REZERO',
        'TEAM-UNKNOWN', 'TEAM-CHAIFLOW', 'TEAM-VARISHU'
    )
);

DELETE FROM teams WHERE team_code NOT IN (
    'TEAM-ALPHA', 'TEAM-BETA', 'TEAM-2NDPLACE', 'TEAM-BDUCODERS', 'TEAM-CTRL+ESC',
    'TEAM-CYBERTRONS', 'TEAM-DOJISDOMAIN', 'TEAM-DUOSEEKERS', 'TEAM-GAC_WARRIORS',
    'TEAM-GAMMA', 'TEAM-INEVITABLE', 'TEAM-JAMALIANS', 'TEAM-LAZYCODERS',
    'TEAM-NINETEEN', 'TEAM-POWERHITTERS', 'TEAM-PHOENIX', 'TEAM-REZERO',
    'TEAM-UNKNOWN', 'TEAM-CHAIFLOW', 'TEAM-VARISHU'
);

-- 3. Also clear past attempts for the retained teams so all 20 teams start completely fresh
DELETE FROM answer_attempts;
DELETE FROM discovery_submissions;
DELETE FROM team_stage_progress;
DELETE FROM team_level_progress;
DELETE FROM team_riddle_progress;
DELETE FROM team_story_progress;
DELETE FROM hint_usage;
DELETE FROM anti_cheat_events;
DELETE FROM team_anti_cheat_summary;
DELETE FROM score_events;
DELETE FROM game_events;
DELETE FROM game_sessions;

-- 4. Deduplicate any duplicate rows for the 20 official teams, retaining lowest id
DELETE FROM players WHERE team_id IN (
    SELECT id FROM teams t1
    WHERE EXISTS (
        SELECT 1 FROM teams t2
        WHERE t1.team_code = t2.team_code AND t1.id > t2.id
    )
);

DELETE FROM teams t1
WHERE EXISTS (
    SELECT 1 FROM teams t2
    WHERE t1.team_code = t2.team_code AND t1.id > t2.id
);

-- 5. Ensure official event (id = 1) is READY
UPDATE events
SET status = 'READY',
    start_time = COALESCE(start_time, CURRENT_TIMESTAMP),
    updated_at = CURRENT_TIMESTAMP
WHERE id = (SELECT id FROM events ORDER BY id LIMIT 1);
