spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/technical_escape_room}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false
    ignore-migration-patterns: "*:missing"

logging:
  level:
    root: INFO
    com.technicalescaperoom.backend: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
