package com.technicalescaperoom.backend.enums;

public enum WebSocketEventType {
    PLAYER_CONNECTED,
    PLAYER_DISCONNECTED,
    PARTNER_CHALLENGE_COMPLETED,
    STAGE_COMPLETED,
    LEVEL_COMPLETED,
    NEXT_LEVEL_UNLOCKED,
    HINT_UNLOCKED,
    GAME_COMPLETED,
    GAME_STATE_UPDATED,
    RANK_CHANGED,
    PLAYER_READY_CHANGED,
    EVENT_STARTED,
    ANTI_CHEAT_ALERT,
    ANTI_CHEAT_EVENT,
    SCORE_UPDATED,
    SECURITY_INCIDENT,
    STORY_STARTED,
    STORY_SKIPPED,
    STORY_COMPLETED,
    STORY_STATE_SYNC
}
